language: python
python: 2.7
env:
  - TOXENV=py26-1.4
  - TOXENV=py26-1.5
  - TOXENV=py26-1.6
  - TOXENV=py27-1.4
  - TOXENV=py27-1.5
  - TOXENV=py27-1.6
  - TOXENV=py27-1.7
  - TOXENV=py33-1.5
  - TOXENV=py33-1.6
  - TOXENV=py33-1.7
  - TOXENV=pypy-1.4
  - TOXENV=pypy-1.5
  - TOXENV=pypy-1.6
  - TOXENV=pypy-1.7
  - TOXENV=docs
  - TOXENV=flake8
before_install:
  # The following three lines is a fix for travis CI, since it wouldn't be
  # able to install the dependencies correctly.
  # See: https://github.com/travis-ci/travis-ci/issues/2683
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get remove -q -y binutils gdal-bin libproj-dev libgeos-c1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable

  - sudo apt-get -q -y update
  # Required to install Pillow
  - sudo apt-get -q -y install build-essential
  # GIS requirements.
  - sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1
install:
  - pip install tox
script:
  - tox -e $TOXENV
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
