language: python
python: 2.7
env:
  - TOXENV=py26-14
  - TOXENV=py26-15
  - TOXENV=py26-16
  - TOXENV=py27-14
  - TOXENV=py27-15
  - TOXENV=py27-16
  - TOXENV=py27-17
  - TOXENV=py33-15
  - TOXENV=py33-16
  - TOXENV=py33-17
  - TOXENV=pypy-14
  - TOXENV=pypy-15
  - TOXENV=pypy-16
  - TOXENV=pypy-17
  - TOXENV=docs
  - TOXENV=flake8
before_install:
  - sudo apt-get -q -y update
  - sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1
install:
  - pip install tox
script:
  - tox
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
